apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: test-cluster-2
  region: eu-west-3
  
nodeGroups:
  - name: builder
    instanceType: t3.micro
    desiredCapacity: 1
    volumeSize: 5
  - name: server
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 5
